#!/bin/sh
DEV="/dev/"$"lsblk -l | grep -vP "[/|\]]" | awk '{print $1}' | grep -ve NAME | dmenu"
mntDIR="/mnt"
rDIR=$mntDIR
while [ "$rDir" != '.' ]; do
	rDIR=$(ls $DIR -al | grep ^d | awk '{print $9}' | dmenu)
	mntDIR=$mntDIR'/'$rDIR
done
echo $DEV
